-- SCRIPT PARA CRIAR AS TABELAS


CREATE TABLE CATEGORIAS (
	codigo NUMERIC(1) PRIMARY KEY,
	descricao VARCHAR(200)
);

CREATE TABLE EQUIPAMENTOS (
	codigo NUMERIC(3) PRIMARY KEY,
	nome   VARCHAR(100),
	valor_diario NUMERIC(7),
	categoria NUMERIC(1),
	CONSTRAINT fk_CatEquip FOREIGN KEY (categoria) REFERENCES CATEGORIAS (codigo)
);

CREATE TABLE CONSTRUTORAS (
	codigo NUMERIC(2) PRIMARY KEY,
	nome   VARCHAR(100),
	nome_fantasia VARCHAR(100)
);

CREATE TABLE OBRAS (
	codigo NUMERIC(3) PRIMARY KEY,
	logradouro VARCHAR(60),
	numero NUMERIC(4),
	complemento VARCHAR(50),
	nome VARCHAR(100),
	construtora NUMERIC(2),
	CONSTRAINT fk_ConstruObra FOREIGN KEY (construtora) REFERENCES CONSTRUTORAS (codigo)
);

CREATE TABLE TELEFONES (
	telefone NUMERIC(11) PRIMARY KEY,
	construtora NUMERIC(2)
);

CREATE TABLE OBRAS_EQUIPAMENTOS (
	obra 	NUMERIC(3),
	equipamento NUMERIC(3),
	data_inicio VARCHAR(10),
	data_final VARCHAR(10),
	CONSTRAINT fk_EquipObra FOREIGN KEY (equipamento) REFERENCES EQUIPAMENTOS (codigo),
	CONSTRAINT fk_ObraEquip FOREIGN KEY (obra) REFERENCES OBRAS (codigo)
);

CREATE TABLE TRABALHADORES (
	codigo NUMERIC(11) PRIMARY KEY,
	nome VARCHAR(100),
	salario NUMERIC(7,2),
	obra NUMERIC(3),
	CONSTRAINT fk_TrabObra FOREIGN KEY (obra) REFERENCES OBRAS (codigo)
);

-- ADICIONANDO FK A TABELA TELEFONES

ALTER TABLE TELEFONES
ADD CONSTRAINT fk_construTel FOREIGN KEY (construtora) REFERENCES CONSTRUTORAS (CODIGO);